project:
  type: website
  output-dir: docs
  resources:
    - "CSEA-Logo-png"

website:
  title: "CSEA-Wiki"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/csea-lab
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: spacelab
    css: styles.css



