project:
  type: website
  output-dir: docs
  resources:
    - "SPL-Logo.png"

website:
  title: "UF-Open-Science-Wiki"
  image: "SPL-Logo.png"
  navbar:
    logo: "SPL-Logo.png"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/UF-SPLab

format:
  html:
    theme: spacelab
    css: styles.css



